apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: 454374565179.dkr.ecr.us-east-1.amazonaws.com/sanju-project:latest
        resources:
        ports:
        - containerPort: 3000

