apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: my-service
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3005
  selector:
    app: myapp
  type: ClusterIP
status:
  loadBalancer: {}
